# Generated by Django 5.0 on 2023-12-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReBuy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productshots',
            options={'verbose_name': 'Product Shot', 'verbose_name_plural': 'Product Shots'},
        ),
    ]
