# Generated by Django 5.0 on 2023-12-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReBuy', '0002_alter_productshots_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(null=True, upload_to='categories/', verbose_name='Category image'),
        ),
    ]
