# Generated by Django 5.0 on 2023-12-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReBuy', '0004_remove_product_draft_product_daily_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Image name')),
                ('image', models.ImageField(upload_to='main-slider/', verbose_name='Main slider image')),
            ],
            options={
                'verbose_name': 'Main page slider image',
                'verbose_name_plural': 'Main page slider images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.SmallIntegerField(null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='poster',
            field=models.ImageField(upload_to='re-buy/', verbose_name='Poster'),
        ),
    ]
