# Generated by Django 5.0 on 2023-12-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReBuy', '0008_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.BooleanField(default=False, null=True, verbose_name='In Cart'),
        ),
    ]
